---
title: "Gant"
WP: "WP6 – Project management and Quality assurance"
WP_num: "WP6"
Description: This document reports a quality plan that includes the criteria and indicators to take into account in the project development. It aims to provide sufficient mechanisms and instruments approved by mutual agreement to ensure compliance with the project's objectives and indicators with high-quality standards and delimiting decision-making elements. Also, it will specify the means of communication, frequency and the external advisory board that will join the project.
Responsible: Université de Lorraine
Dissemination: Confidential
Date-delivrable: May 30/2025
Quality: D6.1.tex
author: 
  - Prof. Fabio A. Cruz &nbsp;
date: today
date-format: long
keep-tex: false
#geometry: margin=0.2cm, paperheight=11cm, paperwidth=25.5cm
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


\begin{ganttchart}[vgrid,
   y unit title=0.5cm,
   y unit chart=0.5cm,
   x unit=1cm,
   %time slot format=isodate-yearmonth,
   %time slot unit=month,
   title/.append style={draw=none, fill=RoyalBlue!50!black},
   title label font=\sffamily\bfseries\color{white},
   title label node/.append style={below=-1.6ex},
   title left shift=.05,
   title right shift=-.05,
   title height=1,
   bar/.append style={draw=none, fill=OliveGreen!75},
   bar height=.6,
   bar label font=\normalsize\color{black!50},
   group right shift=0,
   group top shift=.6,
   group height=.3,
   group peaks height=.2,
   bar incomplete/.append style={fill=Maroon},
   bar progress label anchor = west,
   bar progress label font = \color{white}\scriptsize
]{1}{10}

\gantttitle[]{Semester (S):}{10}\\  % title 1
\gantttitlelist{"Year 1", "Year 2", "Year 3", "Year 4", "Year 5"}{2}\\ % Semester title
\gantttitlelist{"S1","S2","S3","S4", "S5", "S6", "S7", "S8", "S9", "S10"}{1}\\ % Semester title


% Working package 1
\ganttgroup{WP1: Theoretical baseline analysis for closed-loop urban value chains}{1}{6} \\

\ganttbar[name=1a, progress=0, progress label text={PhD1 + PostDoc1 }]{Closing the data gap:}{1}{3} \\
\ganttbar[name=1b, progress=0, progress label text={PostDoc1  }]{Urban territorial priorities in the frame of ecosystems services.}{2}{6} \\
\ganttmilestone[]{Milestone 1}{9} \\

%\ganttnewline[thick, blue]  

% Working package 2
\ganttgroup{WP2: Maturity and techno-diverstity level of the OSATs for distributed recycling}{2}{8} \\

\ganttbar[name=2a, progress=0, progress label text={PhD2 + PostDoc2 }]{Cross-case studies on technical recycling feasibility with the}{2}{3} \\
\ganttbar[name=2b, progress=0,  progress label text={PhD2 + PostDoc2 }]{Establishment of a maturity in of unit- and system-levels for OSATs }{2}{5} \\
\ganttbar[name=2c, progress=0,  progress label text={PostDoc2 }]{Mapping of new/adapted practices and tools for OSAT adoption:}{3}{8} \\

%\ganttnewline[thick, blue]  

% Working package 3
\ganttgroup{WP3: Pluralistic evaluation of distributed recycling systems}{4}{9} \\

\ganttbar[name=3a, progress=0, progress label text={PostDoc1 + PostDoc2 }]{Identify the techno-ecological synergy for an urban closed-loop supply chain.}{4}{6} \\
\ganttbar[name=3b, progress=0,  progress label text={PostDoc2, }]{Structuring a systems dynamic causal loop model}{4}{7} \\
\ganttbar[name=3c, progress=0,  progress label text={PostDoc1 + PostDoc1  }]{Definition of the plausible hypothesis and evolution scenarios}{7}{8} \\

%\ganttnewline[thick, blue]  

% Working package 4
\ganttgroup{WP4: Experimentation and valuation by the local territory}{5}{10} \\

\ganttbar[name=4a, progress=0,  progress label text={PhD 1 + PhD2 + PostDoc2 }]{Technical experimentation and validation of the System dynamics model}{5}{6} \\
\ganttbar[name=4b, progress=0, progress label text={PhD3 + PostDoc2 }]{Participatory Workshops for a pluralistic valuation}{6}{9} \\
\ganttbar[name=4c, progress=0,  progress label text={PostDoc1, }]{documentation and dissemination to scientific and open communities }{6}{10} \\




% WP1   
\ganttlink{1a}{2a}
\ganttlink{1a}{3a}

\ganttlink{1b}{3a}
\ganttlink{1b}{3c}
\ganttlink{1a}{3a}


%\ganttlink{1b}{}
%\ganttlink{T1.1}{T1.4}
%\ganttlink{T1.1}{T1.5}
%\ganttlink{T1.4}{Mile1}

         

\ganttset{link/.style={OliveGreen}}
\end{ganttchart}

