project:
  type: website
  output-dir: docs
fontsize: 20px
website:
  title: "TechTraPlastiCE"  
  navbar:
    right:
      - href: index.qmd
        text: Home


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true