project:
  type: website
  output-dir: docs
fontsize: 20px
website:
  title: "TechTraPlastiCE"  
  navbar:
    right:
      - href: index.qmd
        text: Home
  page-footer: 
    left: | 
      ![](images/logo/EU.png){width="300px"}     
      Project Ref: Project 101179564 — TechTraPlastiCE — ERASMUS-EDU-2024-CBHE Co-funded by the Erasmus+ Programme of the European Union.
      
      This Project has been funded with support from the European Commission. This website reflects exclusively the views of the authors. The Commission can not be held responsible for any use which can be made of the information contained therein.  
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 


margin-header: |
  ![](images/logo/EU.png)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      margin-width: 300px