project:
  type: website
  output-dir: docs
fontsize: 20px
website:
  title: "TechTraPlastiCE"  
  navbar:
    right:
      - href: index.qmd
        text: Home
body-header: | 
  This page brought to you by <https://example.com>
margin-header: |
  ![](images/logo/EU.png)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      margin-width: 300px