---
title: "Strengthening University tech transfer capabilities to support circular economy value chains for plastics in Latin America -- TechTraPlastiCE"
subtitle: "Université de Lorraine"
title-block-banner: images/nancy/Nancy-destination-00.jpeg
date: 2025-01-15
date-format: short
author:
  - name: Fabio CRUZ
    affiliations:
      - Université de Lorraine
---




# Welcome to the Kick-Off Meeting at Nancy, France

## **Join us in Nancy, France** !!

### Event Details

This kick-off meeting marks the beginning of an exciting new project aimed at strengthening the role of universities in fostering green transitions within the plastic industry. 
By enhancing research and technological transfer capabilities, this initiative seeks to build sustainable collaborations between academia and socio-economic stakeholders in Colombia, Argentina, and Chile, promoting innovative circular economy practices and impactful recycling interventions. 
Through dynamic knowledge exchanges and progressive technology transfer, we aim to document valuable insights and develop interdisciplinary strategies that benefit both the global South and the European Union.

- **Date:** March 25-27 / 2025
- **Time:** 9-7
- **Location:** Lorraine Fab Living Lab 49 Boulevard d'Austrasie, Nancy, France
- **Description:**


# Organizers